name: Publish package to the Maven Central Repository

on:
  push:
    branches:
      - master
jobs:

  publish:
    name: "Build and Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
     - name: Bump version
        id: bump
        uses: mickem/gh-action-bump-maven-version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}